version: "3.7"
services:
  jdgui:
    build:
      context: .
      dockerfile: Dockerfile-jdgui
    volumes:
      - "./shared:/shared"
      - "/tmp/.X11-unix:/tmp/.X11-unix"

  jsbeautify:
    build:
      context: .
      dockerfile: Dockerfile-jsbeautify

  sslyze:
    image: nablac0d3/sslyze
