version: "3.7"
services:
  agraph:
    image: franzinc/agraph
    shm_size: "1g"
    environment:
      - AGRAPH_SUPER_USER=admin
      - AGRAPH_SUPER_PASSWORD=admin
    ports:
      - "127.0.0.1:10000-10035:10000-10035"
    volumes:
      - "./shared:/shared"

  android-platformtools:
    build:
      context: .
      dockerfile: Dockerfile-android-platformtools
    volumes:
      - "./shared:/shared"
    devices:
      - "/dev/bus"

  apktool:
    build:
      context: .
      dockerfile: Dockerfile-apktool
    volumes:
      - "./shared:/shared"

  cewl:
    build:
      context: .
      dockerfile: Dockerfile-cewl

  evil-winrm:
    image: oscarakaelvis/evil-winrm

  ffuf:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile-ffuf
    volumes:
      - "./shared:/shared"

  hydra:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile-hydra
    volumes:
      - "./shared:/shared"

  ilspy:
    build:
      context: .
      dockerfile: Dockerfile-ilspy
    volumes:
      - "./shared:/shared"
      - "/tmp/.X11-unix:/tmp/.X11-unix"

  iisshortname:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile-iisshortname
    volumes:
      - "./shared:/shared"

  impacket:
    build:
      context: .
      dockerfile: Dockerfile-impacket

  jadx:
    build:
      context: .
      dockerfile: Dockerfile-jadx
    volumes:
      - "./shared:/shared"
      - "/tmp/.X11-unix:/tmp/.X11-unix"

  jdgui:
    build:
      context: .
      dockerfile: Dockerfile-jdgui
    volumes:
      - "./shared:/shared"
      - "/tmp/.X11-unix:/tmp/.X11-unix"

  john:
    build:
      context: .
      dockerfile: Dockerfile-john
    volumes:
      - "./shared:/shared"

  jsbeautify:
    build:
      context: .
      dockerfile: Dockerfile-jsbeautify

  masscan:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile-masscan

  msfconsole:
    image: metasploitframework/metasploit-framework
    volumes:
      - "./shared:/shared"

  nmap:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile-nmap

  peepdf:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile-peepdf
    working_dir: /shared
    volumes:
      - "./shared:/shared"

  python:
    image: python:3
    command: /bin/bash
    working_dir: /shared
    volumes:
      - "./shared:/shared"

  soapui:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile-soapui
    working_dir: /shared
    volumes:
      - "./shared:/shared"
      - "/tmp/.X11-unix:/tmp/.X11-unix"

  sourcegraph:
    image: sourcegraph/server:3.35.1
    ports:
      - "7080:7080"
      - "3070:3070"
    volumes:
      - ./shared/sourcegraph/config:/etc/sourcegraph
      - ./shared/sourcegraph/data:/var/opt/sourcegraph
      - ./shared/sourcegraph/repos:/repos:ro

  sqlmap:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile-sqlmap
    working_dir: /shared
    volumes:
      - "./shared:/shared"

  ssh_scan:
    image: mozilla/ssh_scan

  sslyze:
    image: nablac0d3/sslyze

  steghide:
    build:
      context: .
      dockerfile: Dockerfile-steghide
    volumes:
      - "./shared:/shared"

  testssl:
    image: drwetter/testssl.sh

  wireshark:
    build:
      context: .
      dockerfile: Dockerfile-wireshark
    volumes:
      - "./shared:/shared"
      - "/tmp/.X11-unix:/tmp/.X11-unix"

  wpscan:
    image: wpscanteam/wpscan
