version: "3.7"
services:
  agraph:
    image: franzinc/agraph
    shm_size: "1g"
    environment:
      - AGRAPH_SUPER_USER=admin
      - AGRAPH_SUPER_PASSWORD=admin
    ports:
      - "127.0.0.1:10000-10035:10000-10035"
    volumes:
      - "./shared:/shared"

  android-platformtools:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile-android-platformtools
    volumes:
      - "./shared:/shared"

  androidstudio:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile-androidstudio
    volumes:
      - "./shared:/shared"
      - "/tmp/.X11-unix:/tmp/.X11-unix"

  apktool:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile-apktool
    volumes:
      - "./shared:/shared"

  cewl:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile-cewl

  cfr:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile-cfr
    volumes:
      - "./shared:/shared"

  dvcs-pillage:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile-dvcs-pillage
    volumes:
      - "./shared:/shared"

  evil-winrm:
    image: oscarakaelvis/evil-winrm

  ffuf:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile-ffuf
    volumes:
      - "./shared:/shared"

  frida:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile-frida
    volumes:
      - "./shared:/shared"

  ghidra:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile-ghidra
    volumes:
      - "./shared:/shared"
      - "/tmp/.X11-unix:/tmp/.X11-unix"

  hydra:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile-hydra
    volumes:
      - "./shared:/shared"

  ilspy:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile-ilspy
    volumes:
      - "./shared:/shared"
      - "/tmp/.X11-unix:/tmp/.X11-unix"

  iisshortname:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile-iisshortname
    volumes:
      - "./shared:/shared"

  impacket:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile-impacket

  insomnia:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile-insomnia
    volumes:
      - "./shared:/shared"
      - "/tmp/.X11-unix:/tmp/.X11-unix"

  jadx:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile-jadx
    volumes:
      - "./shared:/shared"
      - "/tmp/.X11-unix:/tmp/.X11-unix"

  jdgui:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile-jdgui
    volumes:
      - "./shared:/shared"
      - "/tmp/.X11-unix:/tmp/.X11-unix"

  john:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile-john
    volumes:
      - "./shared:/shared"

  jsbeautify:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile-jsbeautify

  lynx:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile-lynx

  masscan:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile-masscan

  msfconsole:
    image: metasploitframework/metasploit-framework
    volumes:
      - "./shared:/shared"

  nmap:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile-nmap

  peepdf:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile-peepdf
    working_dir: /shared
    volumes:
      - "./shared:/shared"

  php:
    image: php
    command: /bin/bash
    working_dir: /shared
    volumes:
      - "./shared:/shared"

  python:
    image: python:3
    command: /bin/bash
    working_dir: /shared
    volumes:
      - "./shared:/shared"

  soapui:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile-soapui
    working_dir: /shared
    volumes:
      - "./shared:/shared"
      - "/tmp/.X11-unix:/tmp/.X11-unix"

  sourcegraph:
    image: sourcegraph/server:3.40.1
    ports:
      - "7080:7080"
      - "3070:3070"
    volumes:
      - ./shared/sourcegraph/config:/etc/sourcegraph
      - ./shared/sourcegraph/data:/var/opt/sourcegraph
      - ./shared/sourcegraph/repos:/repos:ro

  sourcegraph_servegit:
    image: sourcegraph/src-cli
    volumes:
      - ./shared/servegit:/src
    entrypoint: src serve-git /src

  sqlmap:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile-sqlmap
    working_dir: /shared
    volumes:
      - "./shared:/shared"

  ssh_scan:
    image: mozilla/ssh_scan

  sslyze:
    image: nablac0d3/sslyze

  steghide:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile-steghide
    volumes:
      - "./shared:/shared"

  testssl:
    image: drwetter/testssl.sh

  wireshark:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile-wireshark
    volumes:
      - "./shared:/shared"
      - "/tmp/.X11-unix:/tmp/.X11-unix"

  wpscan:
    image: wpscanteam/wpscan

  xcat:
    image: tomforbes/xcat
    working_dir: /shared
    volumes:
      - "./shared:/shared"
