version: "3.7"
services:
  android-platformtools:
    build:
      context: .
      dockerfile: Dockerfile-android-platformtools
    volumes:
      - "./shared:/shared"
    devices:
      - "/dev/bus"

  apktool:
    build:
      context: .
      dockerfile: Dockerfile-apktool
    volumes:
      - "./shared:/shared"

  jadx:
    build:
      context: .
      dockerfile: Dockerfile-jadx
    volumes:
      - "./shared:/shared"
      - "/tmp/.X11-unix:/tmp/.X11-unix"

  jdgui:
    build:
      context: .
      dockerfile: Dockerfile-jdgui
    volumes:
      - "./shared:/shared"
      - "/tmp/.X11-unix:/tmp/.X11-unix"

  jsbeautify:
    build:
      context: .
      dockerfile: Dockerfile-jsbeautify

  sslyze:
    image: nablac0d3/sslyze
