FROM alpine

RUN \
    apk add --no-cache curl && \
    curl -L https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.5.0.jar -o /apktool.jar

FROM openjdk:8-alpine

RUN apk add --no-cache ttf-dejavu

COPY --from=0 /apktool.jar /apktool.jar

WORKDIR /shared

ENTRYPOINT ["java", "-jar", "/apktool.jar"]
