FROM alpine

RUN \
	apk add --no-cache \
		curl \
		unzip \
	&& curl -L https://github.com/skylot/jadx/releases/download/v1.3.4/jadx-1.3.4.zip -o /jadx.zip \
	&& unzip /jadx.zip -d /jadx

FROM openjdk:8-alpine

RUN \
	apk add --no-cache \
		ttf-dejavu \
		xauth \
	&& echo '#!/bin/sh' > /start.sh \
	&& echo 'xauth add $DISPLAY . $MAGICCOOKIE && /jadx/bin/jadx-gui' >> /start.sh \
	&& chmod ugo+x /start.sh

COPY --from=0 /jadx /jadx

ENTRYPOINT ["/start.sh"]
