FROM debian:latest

RUN \
	apt-get update \
	&& apt-get install -y \
		libxext6 \
		libxrender1 \
		libxtst6 \
		libfreetype6 \
		qemu-system-x86 \
        	usbutils \
		wget \
		xauth \
	&& wget https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2021.1.1.20/android-studio-2021.1.1.20-linux.tar.gz \
	&& tar zxf android-studio-2021.1.1.20-linux.tar.gz \
	&& echo '#!/bin/sh' > /start.sh \
	&& echo 'xauth add $DISPLAY . $MAGICCOOKIE && /android-studio/bin/studio.sh' >> /start.sh \
	&& chmod ugo+x /start.sh

WORKDIR /shared

ENTRYPOINT ["/start.sh"]
